<?php

class M_order_rad_details_jasmed extends CI_Model {

    public function __construct() {
        parent::__construct();
        $this->_table = "order_rad_details_jasmed";
    }

    public function findByOrderDetailId($orderDetailId, $idBtMasterJasmed)
    {
        $dataRaw = $this->db
            ->select('
                order_rad_details_jasmed.id as id,
                order_rad_details_jasmed.id_bt_master_jasmed as id_bt_master_jasmed,
                order_rad_details_jasmed.id_order_rad_details as id_order_rad_details,
                order_rad_details_jasmed.id_users_karyawan as id_users_karyawan,
                order_rad_details_jasmed.nilai_order_rad_jasmed as nilai_order_rad_jasmed,
                order_rad_details_jasmed.nilai_discount_jasmed as nilai_discount_jasmed,
                bt_master_jasmed.id as bt_master_jasmed_id,
                bt_master_jasmed.nama_master_jasmed as bt_master_jasmed_nama_master_jasmed,
                users_profile.user_id as users_profile_user_id,
                users_profile.no_rm as users_profile_no_rm,
                users_profile.rs_key as users_profile_rs_key,
                users_profile.pin as users_profile_pin,
                users_profile.password as users_profile_password,
                users_profile.bpjs_id as users_profile_bpjs_id,
                users_profile.number_id as users_profile_number_id,
                users_profile.mobile_phone as users_profile_mobile_phone,
                users_profile.full_name as users_profile_full_name,
                users_profile.id_kel_backup as users_profile_id_kel_backup,
                users_profile.id_kel as users_profile_id_kel,
                users_profile.nama_kk as users_profile_nama_kk,
                users_profile.id_ref_kewarganegaraan as users_profile_id_ref_kewarganegaraan,
                users_profile.hakKelas as users_profile_hakKelas,
                users_profile.kodeHakKelas as users_profile_kodeHakKelas,
                users_profile.jenisPekerjaan as users_profile_jenisPekerjaan,
                users_profile.kodeJenisPekerjaan as users_profile_kodeJenisPekerjaan,
                users_profile.pisa as users_profile_pisa,
                users_profile.kdProvider as users_profile_kdProvider,
                users_profile.nmProvider as users_profile_nmProvider,
                users_profile.dob as users_profile_dob,
                users_profile.date_meninggal as users_profile_date_meninggal,
                users_profile.id_users_profile_details_meninggal as users_profile_id_users_profile_details_meninggal,
                users_profile.kode_dokter_bpjs as users_profile_kode_dokter_bpjs,
                users_profile.gender as users_profile_gender,
                users_profile.tglTAT as users_profile_tglTAT,
                users_profile.tglTMT as users_profile_tglTMT,
                users_profile.nama_kepala_keluarga as users_profile_nama_kepala_keluarga,
                users_profile.bpjs_cob_nmAsuransi as users_profile_bpjs_cob_nmAsuransi,
                users_profile.bpjs_cob_noAsuransi as users_profile_bpjs_cob_noAsuransi,
                users_profile.bpjs_cob_tglTAT as users_profile_bpjs_cob_tglTAT,
                users_profile.bpjs_cob_tglTMT as users_profile_bpjs_cob_tglTMT,
                users_profile.bpjs_informasi_dinsos as users_profile_bpjs_informasi_dinsos,
                users_profile.bpjs_informasi_noSKTM as users_profile_bpjs_informasi_noSKTM,
                users_profile.bpjs_informasi_prolanisPRB as users_profile_bpjs_informasi_prolanisPRB,
                users_profile.bpjs_jenisPeserta_keterangan as users_profile_bpjs_jenisPeserta_keterangan,
                users_profile.bpjs_jenisPeserta_kode as users_profile_bpjs_jenisPeserta_kode,
                users_profile.bpjs_umurSaatPelayanan as users_profile_bpjs_umurSaatPelayanan,
                users_profile.bpjs_umurSekarang as users_profile_bpjs_umurSekarang,
                users_profile.bpjs_tglCetakKartu as users_profile_bpjs_tglCetakKartu,
                users_profile.reg_date as users_profile_reg_date,
                users_profile.gelar_belakang as users_profile_gelar_belakang,
                users_profile.gelar_depan as users_profile_gelar_depan,
                users_profile.berat_lahir as users_profile_berat_lahir,
                users_profile.pob as users_profile_pob,
                users_profile.jenis_pns as users_profile_jenis_pns,
                users_profile.pangkat as users_profile_pangkat,
                users_profile.buta_warna as users_profile_buta_warna,
                users_profile.satuan_kerja as users_profile_satuan_kerja,
                users_profile.z_material_status as users_profile_z_material_status,
                users_profile.marital_status as users_profile_marital_status,
                users_profile.emergency_contact_name as users_profile_emergency_contact_name,
                users_profile.emergency_contact_phone as users_profile_emergency_contact_phone,
                users_profile.emergency_contact_address as users_profile_emergency_contact_address,
                users_profile.emergency_contact_relationship_to_patient as users_profile_emergency_contact_relationship_to_patient,
                users_profile.emergency_contact_no_ktp as users_profile_emergency_contact_no_ktp,
                users_profile.email as users_profile_email,
                users_profile.blood_type as users_profile_blood_type,
                users_profile.smoking_status as users_profile_smoking_status,
                users_profile.religion as users_profile_religion,
                users_profile.education as users_profile_education,
                users_profile.occupation as users_profile_occupation,
                users_profile.spouse_name as users_profile_spouse_name,
                users_profile.rt_rw as users_profile_rt_rw,
                users_profile.address as users_profile_address,
                users_profile.z_province as users_profile_z_province,
                users_profile.z_type_id as users_profile_z_type_id,
                users_profile.z_jml_anak as users_profile_z_jml_anak,
                users_profile.z_city as users_profile_z_city,
                users_profile.z_districts as users_profile_z_districts,
                users_profile.z_village as users_profile_z_village,
                users_profile.z_country as users_profile_z_country,
                users_profile.company_name as users_profile_company_name,
                users_profile.office_address as users_profile_office_address,
                users_profile.office_phone as users_profile_office_phone,
                users_profile.e_full_name as users_profile_e_full_name,
                users_profile.e_phone as users_profile_e_phone,
                users_profile.click_counter as users_profile_click_counter,
                users_profile.zip_code as users_profile_zip_code,
                users_profile.digital_signature as users_profile_digital_signature,
                users_profile.z_is_meninggal as users_profile_z_is_meninggal,
            ')
            ->from($this->_table)
            ->join('bt_master_jasmed', 'order_rad_details_jasmed.id_bt_master_jasmedbt_master_jasmed.id')
            ->join('users_profile', 'order_rad_details_jasmed.id_users_karyawanusers_profile.user_id')
            ->where('order_rad_details_jasmed.id_order_rad_details', $orderDetailId);
        if (!empty($idBtMasterJasmed)) {
            $dataRaw->where('order_rad_details_jasmed.id_bt_master_jasmed', $idBtMasterJasmed);
        }

        $dataRaw = $dataRaw->get()->result_array();

        $data = [];
        if (!empty($dataRaw)) {
            foreach ($dataRaw as $k => $v) {
                $data[] = [
                    'id' => $v['id'],
                    'id_bt_master_jasmed' => [
                        'jasmed_id' => $v['bt_master_jasmed_id'],
                        'jasmed_nama_master_jasmed' => $v['bt_master_jasmed_nama_master_jasmed'],
                    ],
                    'id_order_rad_details' => $v['id_order_rad_details'],
                    'id_users_karyawan' => [
                        'user_id' => $v['users_profile_user_id'],
                        'no_rm' => $v['users_profile_no_rm'],
                        'rs_key' => $v['users_profile_rs_key'],
                        'pin' => $v['users_profile_pin'],
                        'password' => $v['users_profile_password'],
                        'bpjs_id' => $v['users_profile_bpjs_id'],
                        'number_id' => $v['users_profile_number_id'],
                        'mobile_phone' => $v['users_profile_mobile_phone'],
                        'full_name' => $v['users_profile_full_name'],
                        'id_kel_backup' => $v['users_profile_id_kel_backup'],
                        'id_kel' => $v['users_profile_id_kel'],
                        'nama_kk' => $v['users_profile_nama_kk'],
                        'id_ref_kewarganegaraan' => $v['users_profile_id_ref_kewarganegaraan'],
                        'hakKelas' => $v['users_profile_hakKelas'],
                        'kodeHakKelas' => $v['users_profile_kodeHakKelas'],
                        'jenisPekerjaan' => $v['users_profile_jenisPekerjaan'],
                        'kodeJenisPekerjaan' => $v['users_profile_kodeJenisPekerjaan'],
                        'pisa' => $v['users_profile_pisa'],
                        'kdProvider' => $v['users_profile_kdProvider'],
                        'nmProvider' => $v['users_profile_nmProvider'],
                        'dob' => $v['users_profile_dob'],
                        'date_meninggal' => $v['users_profile_date_meninggal'],
                        'id_users_profile_details_meninggal' => $v['users_profile_id_users_profile_details_meninggal'],
                        'kode_dokter_bpjs' => $v['users_profile_kode_dokter_bpjs'],
                        'gender' => $v['users_profile_gender'],
                        'tglTAT' => $v['users_profile_tglTAT'],
                        'tglTMT' => $v['users_profile_tglTMT'],
                        'nama_kepala_keluarga' => $v['users_profile_nama_kepala_keluarga'],
                        'bpjs_cob_nmAsuransi' => $v['users_profile_bpjs_cob_nmAsuransi'],
                        'bpjs_cob_noAsuransi' => $v['users_profile_bpjs_cob_noAsuransi'],
                        'bpjs_cob_tglTAT' => $v['users_profile_bpjs_cob_tglTAT'],
                        'bpjs_cob_tglTMT' => $v['users_profile_bpjs_cob_tglTMT'],
                        'bpjs_informasi_dinsos' => $v['users_profile_bpjs_informasi_dinsos'],
                        'bpjs_informasi_noSKTM' => $v['users_profile_bpjs_informasi_noSKTM'],
                        'bpjs_informasi_prolanisPRB' => $v['users_profile_bpjs_informasi_prolanisPRB'],
                        'bpjs_jenisPeserta_keterangan' => $v['users_profile_bpjs_jenisPeserta_keterangan'],
                        'bpjs_jenisPeserta_kode' => $v['users_profile_bpjs_jenisPeserta_kode'],
                        'bpjs_umurSaatPelayanan' => $v['users_profile_bpjs_umurSaatPelayanan'],
                        'bpjs_umurSekarang' => $v['users_profile_bpjs_umurSekarang'],
                        'bpjs_tglCetakKartu' => $v['users_profile_bpjs_tglCetakKartu'],
                        'reg_date' => $v['users_profile_reg_date'],
                        'gelar_belakang' => $v['users_profile_gelar_belakang'],
                        'gelar_depan' => $v['users_profile_gelar_depan'],
                        'berat_lahir' => $v['users_profile_berat_lahir'],
                        'pob' => $v['users_profile_pob'],
                        'jenis_pns' => $v['users_profile_jenis_pns'],
                        'pangkat' => $v['users_profile_pangkat'],
                        'buta_warna' => $v['users_profile_buta_warna'],
                        'satuan_kerja' => $v['users_profile_satuan_kerja'],
                        'z_material_status' => $v['users_profile_z_material_status'],
                        'marital_status' => $v['users_profile_marital_status'],
                        'emergency_contact_name' => $v['users_profile_emergency_contact_name'],
                        'emergency_contact_phone' => $v['users_profile_emergency_contact_phone'],
                        'emergency_contact_address' => $v['users_profile_emergency_contact_address'],
                        'emergency_contact_relationship_to_patient' => $v['users_profile_emergency_contact_relationship_to_patient'],
                        'emergency_contact_no_ktp' => $v['users_profile_emergency_contact_no_ktp'],
                        'email' => $v['users_profile_email'],
                        'blood_type' => $v['users_profile_blood_type'],
                        'smoking_status' => $v['users_profile_smoking_status'],
                        'religion' => $v['users_profile_religion'],
                        'education' => $v['users_profile_education'],
                        'occupation' => $v['users_profile_occupation'],
                        'spouse_name' => $v['users_profile_spouse_name'],
                        'rt_rw' => $v['users_profile_rt_rw'],
                        'address' => $v['users_profile_address'],
                        'z_province' => $v['users_profile_z_province'],
                        'z_type_id' => $v['users_profile_z_type_id'],
                        'z_jml_anak' => $v['users_profile_z_jml_anak'],
                        'z_city' => $v['users_profile_z_city'],
                        'z_districts' => $v['users_profile_z_districts'],
                        'z_village' => $v['users_profile_z_village'],
                        'z_country' => $v['users_profile_z_country'],
                        'company_name' => $v['users_profile_company_name'],
                        'office_address' => $v['users_profile_office_address'],
                        'office_phone' => $v['users_profile_office_phone'],
                        'e_full_name' => $v['users_profile_e_full_name'],
                        'e_phone' => $v['users_profile_e_phone'],
                        'click_counter' => $v['users_profile_click_counter'],
                        'zip_code' => $v['users_profile_zip_code'],
                        'digital_signature' => $v['users_profile_digital_signature'],
                        'z_is_meninggal' => $v['users_profile_z_is_meninggal'],
                    ],
                    'nilai_order_rad_jasmed' => $v['nilai_order_rad_jasmed'],
                    'nilai_discount_jasmed' => $v['nilai_discount_jasmed'],
                    'bt_master_jasmed_id' => $v['bt_master_jasmed_id'],
                    'bt_master_jasmed_nama_master_jasmed' => $v['bt_master_jasmed_nama_master_jasmed']                
                ];
            }
        }
        return $data;
    }
}
